### ISSUE TITLE
Setting up locally with docker-compose fails

### ISSUE THREAD

**Issue by raj-dhamsaniya** [harness/harness-core#53743]
I want to setup harness locally. For that, I believe I can do it using this docker compose setup. https://github.com/harness/harness-core/tree/develop/cd-community#harness-community-edition---docker-compose

I was able to do it with docker compose up command which fetches the image from the cloud and starts it.
Now, I want to modify some things in code and check if its working, in that case when I do `./cd-community/build.sh` it fails to build those images.

Do we have any docs for building and testing it locally with easy enough setup.

fyi, I tried setting up in local with this readme https://github.com/harness/harness-core/blob/develop/README.md and I was able to run command `bazel build :all` successfully as well. based onn the older issue I tried running ` bazel build //...` as well which was successful, but I’m not able to figure out how I can change a bit of code and then deploy it. Any help for the same?!

When I tru to run the `./cd-community/build.sh` command it gives error as 
```
  /Users/rajdhamsaniya/Git/raj-dhamsaniya/harness-core/WORKSPACE:5787:23: in <toplevel>
  /private/var/tmp/_bazel_rajdhamsaniya/9ba0df0d45c05352761662449bc8699e/external/io_bazel_rules_docker/repositories/repositories.bzl:60:18: in repositories
Repository rule http_file defined at:
  /private/var/tmp/_bazel_rajdhamsaniya/9ba0df0d45c05352761662449bc8699e/external/bazel_tools/tools/build_defs/repo/http.bzl:466:28: in <toplevel>
ERROR: /Users/rajdhamsaniya/Git/raj-dhamsaniya/harness-core/pipeline-service/container/BUILD.bazel:24:8: no such package 'pipeline-service/src/main/resources': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/rajdhamsaniya/Git/raj-dhamsaniya/harness-core/pipeline-service/src/main/resources and referenced by '//pipeline-service/container:files'
ERROR: Analysis of target '//pipeline-service/container:push' failed; build aborted: 
```

My machine is m1 silicon.

**Comment by gn-harness** [comment]
Hey @raj-dhamsaniya ! we are retiring CD community in favor of Gitness. Please see https://www.harness.io/blog/retiring-harness-cd-community-edition-in-favor-of-gitness

**Comment by raj-dhamsaniya** [comment]
> Hey @raj-dhamsaniya ! we are retiring CD community in favor of Gitness. Please see https://www.harness.io/blog/retiring-harness-cd-community-edition-in-favor-of-gitness

@gn-harness Got it. will go through it. I didn't see any deadline for the same on making this repo private. Is there any date set? I wanted to get the idea of the software of NG, for which I believe the commits are happening in this repo only and wanted to run it locally for testing and development. LMK if that would be restricted as well or we can do it?!
